on:
    push:
      tags:
        - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    container: codebrudi42/codebrudi-dotnet-build:latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set VERSION variable from tag
        shell: bash
        run: |
          TAG=${{github.ref_name}}
          echo VERSION=${TAG:1} >> $GITHUB_ENV
      - name: Pack
        run: dotnet Blazorbrudi/Blazorbrudi.csproj pack --configuration Release /p:Version=${VERSION} --output .
      - name: Push
        run: dotnet nuget push ./*.nupkg --source ${NUGET_REPOSITORY} --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_REPOSITORY: ${{ secrets.NUGET_REPOSITORY }}
